{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  labels: {{- include "pa.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  CLICKHOUSE_USER: {{ .Values.secrets.clickhouseUser | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.secrets.clickhousePassword | quote }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.secrets.grafanaAdminPassword | quote }}
  pgDsn: {{ printf "postgresql://%s:%s@postgres:5432/%s" .Values.secrets.postgresUser .Values.secrets.postgresPassword .Values.config.postgresDb | quote }}
  chUrl: {{ printf "http://%s:%s@clickhouse:8123" .Values.secrets.clickhouseUser .Values.secrets.clickhousePassword | quote }}
{{- end }}
